name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - "composer.*"
env:
  INSTALL_DIR: /srv/www/civi-zero
jobs:
  build:
    name: Build CiviCRM
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR}
