name: build
on:
  pull_request:
    branches:
      - main
    paths:
      - "composer.*"
env:
  INSTALL_DIR: /srv/www/civi-zero
jobs:
  build:
    name: Build CiviCRM
    runs-on: ubuntu-20.04
    steps:
      - name: Purge MySQL databases
        run: |
          sudo systemctl stop mysql
          sudo rm -rf /var/lib/mysql

      - name: Get civi-zero
        uses: actions/checkout@v3

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR}
