name: build
on:
  pull_request:
    branches:
      - main
    paths:
      - "composer.*"
env:
  WEBROOT: "/srv/www"
  CIVI_DIR: "civi-zero"
jobs:
  build:
    name: Build CiviCRM
    runs-on: ubuntu-20.04
    steps:
      - name: Purge MySQL databases
        run: |
          sudo systemctl stop mysql
          sudo rm -rf /var/lib/mysql

      - name: Get civi-zero
        uses: actions/checkout@v3
        with:
          path: "${{ env.CIVI_DIR }}"

      - name: Move civi-zero to web root
        run: |
          sudo mkdir -p "${WEBROOT}"
          sudo mv "${CIVI_DIR}" "${WEBROOT}/"
          sudo chown -R "${USER}" "${WEBROOT}/${CIVI_DIR}"

      - name: Setup environment
        run: "${WEBROOT}/${CIVI_DIR}/bin/prepare.sh"

      - name: Install CiviCRM
        run: "${WEBROOT}/${CIVI_DIR}/bin/install.sh ${WEBROOT}/${CIVI_DIR}"
