name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - "composer.*"
env:
  INSTALL_DIR: /srv/www/civi-zero
  COMPOSER_CACHE_DIR: ~/.composer/cache
  TERM: xterm-256color
jobs:
  build:
    name: Build CiviCRM
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v4

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR}
