name: CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/**'
env:
  WEBROOT: "/srv/www"
  CIVI_DIR: "civi-zero"
jobs:
  code-style:
    name: Check code style (beautysh)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          args: 'bin/*.sh --check'
  linter:
    name: Linter (shellcheck)
    runs-on: ubuntu-20.04
    needs: code-style
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
        env:
          SHELLCHECK_OPTS: -s bash
  build:
    name: Build CiviCRM, run a unit test (rc-base)
    runs-on: ubuntu-20.04
    needs:
      - code-style
      - linter
    steps:
      - name: Purge MySQL databases
        run: |
          sudo systemctl stop mysql
          sudo rm -rf /var/lib/mysql

      - name: Get civi-zero
        uses: actions/checkout@v3
        with:
          path: "${{ env.CIVI_DIR }}"

      - name: Move civi-zero to web root
        run: |
          sudo mkdir -p "${{ env.WEBROOT }}"
          sudo mv "${{ env.CIVI_DIR }}" "${{ env.WEBROOT }}/"
          sudo chown -R "${USER}" "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}"

      - name: Setup environment
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/prepare.sh"

      - name: Install CiviCRM
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/install.sh ${{ env.WEBROOT }}/${{ env.CIVI_DIR }} --sample"

      - name: Reinstall CiviCRM
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/reinstall.sh ${{ env.WEBROOT }}/${{ env.CIVI_DIR }} --sample"

      - name: Get required extension (rc-base)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/rc-base
          path: rc-base

      - name: Install extensions
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/extension.sh ${{ env.WEBROOT }}/${{ env.CIVI_DIR }} rc-base"

      - name: Run unit tests
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/tests.sh ${{ env.WEBROOT }}/${{ env.CIVI_DIR }} rc-base"
