name: CI
on:
  pull_request:
    branches: [ main ]
env:
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: civi_zero
  WEBROOT: "/srv/www"
  CIVI_DIR: "civi-zero"
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Start MySQL
        run: |
          sudo systemctl start mysql

      - name: Check out civi-zero
        uses: actions/checkout@v3
        with:
          path: "${{ env.CIVI_DIR }}"

      - name: Move civi-zero to web root
        run: |
          sudo mkdir -p "${{ env.WEBROOT }}"
          sudo mv "${{ env.CIVI_DIR }}" "${{ env.WEBROOT }}/"
          sudo chown -R "${USER}" "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}"

      - name: Setup environment
        run: "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/prepare.sh"

      - name: Install CiviCRM
        run: |
          "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}/bin/install.sh" \
            "${{ env.WEBROOT }}/${{ env.CIVI_DIR }}" \
            "${{ env.DB_USER }}" \
            "${{ env.DB_PASSWORD }}" \
            "${{ env.DB_NAME }}"

#      - name: Check out the code
#        uses: actions/checkout@v2
#        with:
#          path: ${{ env.EXTENSION_NAME }}
#
#      - name: Move code under extensions directory
#        run: |
#          sudo mv ${{ env.EXTENSION_NAME }} ${{ env.LOCAL_DEPLOY_TARGET }}"/"${{ env.SITE_NAME }}"/web/sites/default/files/civicrm/ext"
#
#      - name: Enable extension
#        run: |
#          cd ${{ env.LOCAL_DEPLOY_TARGET }}"/"${{ env.SITE_NAME }}
#          cv --no-interaction --cwd=${{ env.LOCAL_DEPLOY_TARGET }}/${{ env.SITE_NAME }} ext:enable ${{ env.EXTENSION_NAME }}
#      - name: Run unit tests
#        run: |
#          cd ${{ env.LOCAL_DEPLOY_TARGET }}"/"${{ env.SITE_NAME }}"/web/sites/default/files/civicrm/ext/"${{ env.EXTENSION_NAME }}
#          XDEBUG_MODE=coverage XDEBUG_MODE_COVERAGE=coverage phpunit --verbose --coverage-text
