name: Shell
on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
      - "cfg/**"
env:
  INSTALL_DIR: /srv/www/civi-zero
jobs:
  format:
    name: Check format
    runs-on: ubuntu-20.04
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          args: --force-function-style paronly --check bin/*
  linter:
    name: Linter (shellcheck)
    runs-on: ubuntu-20.04
    needs: format
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --external-sources --enable add-default-case,avoid-nullary-conditions,check-extra-masked-returns,check-set-e-suppressed,deprecate-which,quote-safe-variables,require-double-brackets,require-variable-braces --shell bash
        with:
          severity: style
  tests:
    name: Tests scripts
    runs-on: ubuntu-20.04
    needs:
      - format
      - linter
    steps:
      - name: Get civi-zero
        uses: actions/checkout@v3

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR} --sample

      - name: Init test DB
        run: ./bin/init-test-DB.sh ${INSTALL_DIR}

      - name: Reinstall CiviCRM
        run: ./bin/reinstall.sh ${INSTALL_DIR} --sample

      - name: Get required extension (uk.co.vedaconsulting.mosaico)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/uk.co.vedaconsulting.mosaico
          path: uk.co.vedaconsulting.mosaico
          ref: build

      - name: Get test extension (rc-mosaico-template)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/rc-mosaico-template
          path: rc-mosaico-template

      - name: Install extensions
        run: |
          ./bin/extension.sh ${INSTALL_DIR} uk.co.vedaconsulting.mosaico
          ./bin/extension.sh ${INSTALL_DIR} rc-mosaico-template

      - name: Run unit tests
        run: ./bin/tests.sh ${INSTALL_DIR} rc-mosaico-template
