name: tests
on:
  pull_request:
    branches:
      - main
    paths:
      - "bin/**"
      - "cfg/**"
env:
  INSTALL_DIR: /srv/www/civi-zero
jobs:
  code-style:
    name: Check code style (beautysh)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          args: --force-function-style paronly --check bin/*
  linter:
    name: Linter (shellcheck)
    runs-on: ubuntu-20.04
    needs: code-style
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --external-sources --enable add-default-case,avoid-nullary-conditions,check-extra-masked-returns,check-set-e-suppressed,deprecate-which,quote-safe-variables,require-double-brackets,require-variable-braces --shell bash
        with:
          severity: style
  tests:
    name: Tests scripts
    runs-on: ubuntu-20.04
    needs:
      - code-style
      - linter
    steps:
      - name: Purge MySQL databases
        run: |
          sudo systemctl stop mysql
          sudo rm -rf /var/lib/mysql

      - name: Get civi-zero
        uses: actions/checkout@v3

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR} --sample

      - name: Reinstall CiviCRM
        run: ./bin/reinstall.sh ${INSTALL_DIR} --sample

      - name: Get required extension (rc-base)
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/rc-base
          path: rc-base

      - name: Install extensions
        run: ./bin/extension.sh ${INSTALL_DIR} rc-base

      - name: Run unit tests
        run: ./bin/tests.sh ${INSTALL_DIR} rc-base
